owner: KPOPCORD
repo: status

sites:
  - name: SMTOWN
    url: https://www.smtown.com
  - name: SMTOWN Mobile
    url: https://m.smtown.com
  - name: YG LIFE
    url: https://yg-life.com
  - name: Weverse
    url: https://www.weverse.io

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for K-POP"
  introMessage: K-POP Web Monitor
